"""Interactive production deployment helper for AgBlogger."""

from __future__ import annotations

import argparse
import getpass
import json
import os
import secrets
import shutil
import subprocess
import sys
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path

MIN_SECRET_KEY_LENGTH = 32
MIN_ADMIN_PASSWORD_LENGTH = 12
DEFAULT_HOST_PORT = 8000
DEFAULT_ENV_FILE = ".env.production"
DEFAULT_CADDYFILE = "Caddyfile.production"
DEFAULT_NO_CADDY_COMPOSE_FILE = "docker-compose.nocaddy.yml"
DEFAULT_CADDY_PUBLIC_COMPOSE_FILE = "docker-compose.caddy-public.yml"
DEFAULT_IMAGE_COMPOSE_FILE = "docker-compose.image.yml"
DEFAULT_IMAGE_NO_CADDY_COMPOSE_FILE = "docker-compose.image.nocaddy.yml"
DEFAULT_REMOTE_README = "DEPLOY-REMOTE.md"
DEFAULT_IMAGE_TARBALL = "agblogger-image.tar"
DEFAULT_BUNDLE_DIR = Path("dist/deploy")
DEPLOY_MODE_LOCAL = "local"
DEPLOY_MODE_REGISTRY = "registry"
DEPLOY_MODE_TARBALL = "tarball"
DEPLOY_MODES = {DEPLOY_MODE_LOCAL, DEPLOY_MODE_REGISTRY, DEPLOY_MODE_TARBALL}
LOCAL_IMAGE_TAG = "agblogger:latest"
CADDY_STATIC_IP = "172.30.0.2"
COMPOSE_SUBNET = "172.30.0.0/24"
# Constructed to avoid static-analysis tools flagging literal 0.0.0.0
PUBLIC_BIND_IP = ".".join(("0", "0", "0", "0"))
LOCALHOST_BIND_IP = "127.0.0.1"

GENERATED_CONFIG_FILES = [
    DEFAULT_ENV_FILE,
    DEFAULT_CADDYFILE,
    DEFAULT_NO_CADDY_COMPOSE_FILE,
    DEFAULT_CADDY_PUBLIC_COMPOSE_FILE,
]

BUNDLE_CONFIG_FILES = [
    DEFAULT_ENV_FILE,
    DEFAULT_CADDYFILE,
    DEFAULT_CADDY_PUBLIC_COMPOSE_FILE,
    DEFAULT_IMAGE_COMPOSE_FILE,
    DEFAULT_IMAGE_NO_CADDY_COMPOSE_FILE,
    DEFAULT_REMOTE_README,
]


class DeployError(RuntimeError):
    """Raised for deployment workflow failures."""


@dataclass(frozen=True)
class CaddyConfig:
    """Caddy reverse-proxy settings."""

    domain: str
    email: str | None


@dataclass(frozen=True)
class DeployConfig:
    """User-provided production configuration."""

    secret_key: str
    admin_username: str
    admin_password: str
    trusted_hosts: list[str]
    trusted_proxy_ips: list[str]
    host_port: int
    host_bind_ip: str
    caddy_config: CaddyConfig | None
    caddy_public: bool
    expose_docs: bool
    deployment_mode: str = DEPLOY_MODE_LOCAL
    image_ref: str | None = None
    bundle_dir: Path = DEFAULT_BUNDLE_DIR
    tarball_filename: str = DEFAULT_IMAGE_TARBALL


@dataclass(frozen=True)
class DeployResult:
    """Result metadata for a successful deployment."""

    env_path: Path
    commands: dict[str, str]
    bundle_path: Path | None = None


# ── Content builders ─────────────────────────────────────────────────


def parse_csv_list(raw: str) -> list[str]:
    """Parse comma-separated values, trimming whitespace and removing duplicates."""
    values: list[str] = []
    for entry in raw.split(","):
        candidate = entry.strip()
        if candidate and candidate not in values:
            values.append(candidate)
    return values


def _list_to_env_json(values: list[str]) -> str:
    """Serialize list values for pydantic-settings JSON parsing."""
    return json.dumps(values, separators=(",", ":"))


def _quote_env_value(value: str) -> str:
    """Quote scalar env values so special characters stay intact."""
    return json.dumps(value)


def _run_command(
    command: list[str],
    project_dir: Path,
) -> subprocess.CompletedProcess[bytes]:
    """Run a CLI command in the project directory."""
    return subprocess.run(command, cwd=project_dir, check=True)


def _run_docker(project_dir: Path, args: list[str]) -> subprocess.CompletedProcess[bytes]:
    """Run a Docker CLI command in the project directory."""
    return _run_command(["docker", *args], project_dir)


def _run_trivy(project_dir: Path, args: list[str]) -> subprocess.CompletedProcess[bytes]:
    """Run a Trivy CLI command in the project directory."""
    return _run_command(["trivy", *args], project_dir)


def build_env_content(config: DeployConfig) -> str:
    """Build .env file content for production deployment."""
    lines = [
        "# Auto-generated by cli/deploy_production.py",
        f"SECRET_KEY={_quote_env_value(config.secret_key)}",
        f"ADMIN_USERNAME={_quote_env_value(config.admin_username)}",
        f"ADMIN_PASSWORD={_quote_env_value(config.admin_password)}",
        f"HOST_PORT={config.host_port}",
        f"HOST_BIND_IP={config.host_bind_ip}",
        "DEBUG=false",
        f"EXPOSE_DOCS={'true' if config.expose_docs else 'false'}",
        f"TRUSTED_HOSTS={_list_to_env_json(config.trusted_hosts)}",
        f"TRUSTED_PROXY_IPS={_list_to_env_json(config.trusted_proxy_ips)}",
        "AUTH_ENFORCE_LOGIN_ORIGIN=true",
        "AUTH_SELF_REGISTRATION=false",
        "AUTH_INVITES_ENABLED=true",
        "AUTH_LOGIN_MAX_FAILURES=5",
        "AUTH_RATE_LIMIT_WINDOW_SECONDS=300",
    ]
    if config.image_ref is not None:
        lines.append(f"AGBLOGGER_IMAGE={_quote_env_value(config.image_ref)}")
    return "\n".join(lines) + "\n"


def build_caddyfile_content(config: CaddyConfig) -> str:
    """Build Caddyfile content for HTTPS reverse proxy with request body limits."""
    global_block = f"{{\n    email {config.email}\n}}\n\n" if config.email else ""
    return (
        f"{global_block}"
        f"{config.domain} {{\n"
        "    @postUpload path /api/posts/upload\n"
        "    request_body @postUpload {\n"
        "        max_size 55MB\n"
        "    }\n\n"
        "    @postAssets path_regexp post_assets ^/api/posts/.+/assets$\n"
        "    request_body @postAssets {\n"
        "        max_size 55MB\n"
        "    }\n\n"
        "    @syncCommit path /api/sync/commit\n"
        "    request_body @syncCommit {\n"
        "        max_size 100MB\n"
        "    }\n\n"
        "    reverse_proxy agblogger:8000\n\n"
        "    # Static asset caching\n"
        "    header /assets/* {\n"
        '        Cache-Control "public, max-age=31536000, immutable"\n'
        "    }\n\n"
        "    # HTML caching (short TTL for freshness)\n"
        "    @html path_regexp \\.html$\n"
        "    header @html {\n"
        '        Cache-Control "public, max-age=60"\n'
        "    }\n\n"
        "    # API caching\n"
        "    header /api/* {\n"
        '        Cache-Control "no-cache"\n'
        "    }\n\n"
        "    # Compression\n"
        "    encode gzip zstd\n"
        "}\n"
    )


def _is_valid_trusted_host(host: str) -> bool:
    """Return True for explicit hosts and narrow subdomain wildcards."""
    candidate = host.strip()
    if not candidate or candidate == "*":
        return False
    if "*" not in candidate:
        return True
    return candidate.startswith("*.") and candidate.count("*") == 1 and len(candidate) > 2


def _agblogger_env_section() -> str:
    """Return the environment YAML block shared across all compose files."""
    return (
        "    environment:\n"
        "      - SECRET_KEY=${SECRET_KEY?Set SECRET_KEY}\n"
        "      - ADMIN_USERNAME=${ADMIN_USERNAME?Set ADMIN_USERNAME}\n"
        "      - ADMIN_PASSWORD=${ADMIN_PASSWORD?Set ADMIN_PASSWORD}\n"
        "      - TRUSTED_HOSTS=${TRUSTED_HOSTS?Set TRUSTED_HOSTS}\n"
        "      - TRUSTED_PROXY_IPS=${TRUSTED_PROXY_IPS:-[]}\n"
        "      - CONTENT_DIR=/data/content\n"
        "      - DATABASE_URL=sqlite+aiosqlite:////data/db/agblogger.db\n"
        "      - DEBUG=${DEBUG:-false}\n"
        "      - EXPOSE_DOCS=${EXPOSE_DOCS:-false}\n"
        "      - AUTH_ENFORCE_LOGIN_ORIGIN=${AUTH_ENFORCE_LOGIN_ORIGIN:-true}\n"
        "      - AUTH_SELF_REGISTRATION=${AUTH_SELF_REGISTRATION:-false}\n"
        "      - AUTH_INVITES_ENABLED=${AUTH_INVITES_ENABLED:-true}\n"
        "      - AUTH_LOGIN_MAX_FAILURES=${AUTH_LOGIN_MAX_FAILURES:-5}\n"
        "      - AUTH_RATE_LIMIT_WINDOW_SECONDS=${AUTH_RATE_LIMIT_WINDOW_SECONDS:-300}\n"
    )


def _agblogger_healthcheck_section() -> str:
    """Return the restart + healthcheck YAML block for agblogger services."""
    return (
        "    restart: unless-stopped\n"
        "    healthcheck:\n"
        '      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]\n'
        "      interval: 30s\n"
        "      timeout: 5s\n"
        "      start_period: 10s\n"
        "      retries: 3\n"
    )


def _caddy_service_section() -> str:
    """Return the Caddy service YAML block with static proxy IP."""
    return (
        "  caddy:\n"
        "    image: caddy:2\n"
        "    ports:\n"
        '      - "127.0.0.1:80:80"\n'
        '      - "127.0.0.1:443:443"\n'
        "    volumes:\n"
        "      - ./Caddyfile.production:/etc/caddy/Caddyfile:ro\n"
        "      - caddy-data:/data\n"
        "      - caddy-config:/config\n"
        "    depends_on:\n"
        "      agblogger:\n"
        "        condition: service_healthy\n"
        "    restart: unless-stopped\n"
        "    networks:\n"
        "      default:\n"
        f"        ipv4_address: {CADDY_STATIC_IP}\n"
    )


def _compose_network_block() -> str:
    """Return the custom network YAML block for Caddy proxy IP."""
    return (
        "networks:\n"
        "  default:\n"
        "    driver: bridge\n"
        "    ipam:\n"
        "      config:\n"
        f"        - subnet: {COMPOSE_SUBNET}\n"
    )


def build_direct_compose_content() -> str:
    """Build a no-Caddy compose file for direct AgBlogger exposure."""
    return (
        "services:\n"
        "  agblogger:\n"
        "    build: .\n"
        f"    image: {LOCAL_IMAGE_TAG}\n"
        "    user: root\n"
        "    ports:\n"
        '      - "${HOST_BIND_IP:-127.0.0.1}:${HOST_PORT:-8000}:8000"\n'
        "    volumes:\n"
        "      - ./content:/data/content\n"
        "      - agblogger-db:/data/db\n"
        + _agblogger_env_section()
        + _agblogger_healthcheck_section()
        + "\n"
        "volumes:\n"
        "  agblogger-db:\n"
    )


def build_image_compose_content() -> str:
    """Build an image-only Caddy-first compose file for remote deployment."""
    return (
        "services:\n"
        "  agblogger:\n"
        '    image: "${AGBLOGGER_IMAGE?Set AGBLOGGER_IMAGE}"\n'
        "    user: root\n"
        "    expose:\n"
        '      - "8000"\n'
        "    volumes:\n"
        "      - ./content:/data/content\n"
        "      - agblogger-db:/data/db\n"
        + _agblogger_env_section()
        + _agblogger_healthcheck_section()
        + "\n"
        + _caddy_service_section()
        + "\n"
        + _compose_network_block()
        + "\n"
        "volumes:\n"
        "  agblogger-db:\n"
        "  caddy-data:\n"
        "  caddy-config:\n"
    )


def build_image_direct_compose_content() -> str:
    """Build an image-only no-Caddy compose file for remote deployment."""
    return (
        "services:\n"
        "  agblogger:\n"
        '    image: "${AGBLOGGER_IMAGE?Set AGBLOGGER_IMAGE}"\n'
        "    user: root\n"
        "    ports:\n"
        '      - "${HOST_BIND_IP:-127.0.0.1}:${HOST_PORT:-8000}:8000"\n'
        "    volumes:\n"
        "      - ./content:/data/content\n"
        "      - agblogger-db:/data/db\n"
        + _agblogger_env_section()
        + _agblogger_healthcheck_section()
        + "\n"
        "volumes:\n"
        "  agblogger-db:\n"
    )


def build_caddy_public_compose_override_content() -> str:
    """Build compose override that exposes Caddy publicly."""
    return 'services:\n  caddy:\n    ports:\n      - "80:80"\n      - "443:443"\n'


# ── Compose helpers ──────────────────────────────────────────────────


def _compose_filenames(
    deployment_mode: str,
    use_caddy: bool,
    caddy_public: bool,
) -> list[str]:
    """Return compose filenames for the requested deployment mode."""
    if deployment_mode == DEPLOY_MODE_LOCAL:
        if use_caddy and caddy_public:
            return ["docker-compose.yml", DEFAULT_CADDY_PUBLIC_COMPOSE_FILE]
        if use_caddy:
            return ["docker-compose.yml"]
        return [DEFAULT_NO_CADDY_COMPOSE_FILE]

    if use_caddy and caddy_public:
        return [DEFAULT_IMAGE_COMPOSE_FILE, DEFAULT_CADDY_PUBLIC_COMPOSE_FILE]
    if use_caddy:
        return [DEFAULT_IMAGE_COMPOSE_FILE]
    return [DEFAULT_IMAGE_NO_CADDY_COMPOSE_FILE]


def _compose_base_command(
    deployment_mode: str,
    use_caddy: bool,
    caddy_public: bool,
    env_filename: str,
) -> str:
    """Build the shared docker compose command prefix for lifecycle commands."""
    filenames = _compose_filenames(deployment_mode, use_caddy, caddy_public)
    if not filenames:
        return f"docker compose --env-file {env_filename}"

    flags = " ".join(f"-f {name}" for name in filenames)
    return f"docker compose --env-file {env_filename} {flags}"


def build_lifecycle_commands(
    deployment_mode: str,
    use_caddy: bool,
    caddy_public: bool,
    env_filename: str = DEFAULT_ENV_FILE,
    tarball_filename: str = DEFAULT_IMAGE_TARBALL,
) -> dict[str, str]:
    """Build Docker lifecycle commands shown to the user."""
    base = _compose_base_command(deployment_mode, use_caddy, caddy_public, env_filename)
    commands = {
        "start": f"{base} up -d",
        "stop": f"{base} down",
        "status": f"{base} ps",
    }
    if deployment_mode == DEPLOY_MODE_REGISTRY:
        commands["pull"] = f"{base} pull"
    if deployment_mode == DEPLOY_MODE_TARBALL:
        commands["load"] = f"docker load -i {tarball_filename}"
    return commands


# ── Validation ───────────────────────────────────────────────────────


def _validate_config(config: DeployConfig) -> None:
    """Validate required production constraints before writing files."""
    if len(config.secret_key) < MIN_SECRET_KEY_LENGTH:
        raise DeployError(f"SECRET_KEY must have at least {MIN_SECRET_KEY_LENGTH} characters")
    if len(config.admin_password) < MIN_ADMIN_PASSWORD_LENGTH:
        raise DeployError(
            f"ADMIN_PASSWORD must have at least {MIN_ADMIN_PASSWORD_LENGTH} characters"
        )
    if not config.admin_username:
        raise DeployError("ADMIN_USERNAME must not be empty")
    if not config.trusted_hosts:
        raise DeployError("TRUSTED_HOSTS must include at least one host")
    for host in config.trusted_hosts:
        if not _is_valid_trusted_host(host):
            raise DeployError(
                f"Invalid trusted host: {host!r}. "
                "Use explicit hosts or '*.example.com' (no catch-all wildcards)."
            )
    if not (1 <= config.host_port <= 65535):
        raise DeployError("HOST_PORT must be between 1 and 65535")
    if config.host_bind_ip not in {LOCALHOST_BIND_IP, PUBLIC_BIND_IP}:
        raise DeployError(f"HOST_BIND_IP must be either {LOCALHOST_BIND_IP} or {PUBLIC_BIND_IP}")
    if config.caddy_config is not None:
        if "." not in config.caddy_config.domain or " " in config.caddy_config.domain:
            raise DeployError("Caddy domain must be a valid public hostname")
        if config.caddy_config.email and "@" not in config.caddy_config.email:
            raise DeployError("Caddy contact email must contain '@'")
    if config.caddy_public and config.caddy_config is None:
        raise DeployError("Caddy public exposure requires Caddy to be enabled")
    if config.deployment_mode not in DEPLOY_MODES:
        raise DeployError(f"DEPLOYMENT_MODE must be one of: {', '.join(sorted(DEPLOY_MODES))}")
    if config.deployment_mode in {DEPLOY_MODE_REGISTRY, DEPLOY_MODE_TARBALL}:
        if not config.image_ref:
            raise DeployError("IMAGE_REF is required for registry and tarball deployments")
    elif config.image_ref is not None:
        raise DeployError("IMAGE_REF is only supported for registry and tarball deployments")
    if config.image_ref is not None and any(char.isspace() for char in config.image_ref):
        raise DeployError("IMAGE_REF must not contain whitespace")
    if not config.bundle_dir.parts:
        raise DeployError("BUNDLE_DIR must not be empty")
    if config.deployment_mode == DEPLOY_MODE_TARBALL and not config.tarball_filename.strip():
        raise DeployError("TARBALL_FILENAME must not be empty")


def check_prerequisites(project_dir: Path) -> None:
    """Check required deployment prerequisites."""
    compose_file = project_dir / "docker-compose.yml"
    if not compose_file.exists():
        raise DeployError(f"Missing docker compose file: {compose_file}")
    if shutil.which("docker") is None:
        raise DeployError("Docker is not installed or not available on PATH")

    _run_docker(project_dir, ["--version"])
    _run_docker(project_dir, ["compose", "version"])


# ── File management ──────────────────────────────────────────────────


def backup_file(path: Path) -> Path | None:
    """Create a .bak backup of a file if it exists. Returns backup path or None."""
    if not path.exists():
        return None
    backup_path = path.with_suffix(path.suffix + ".bak")
    shutil.copy2(path, backup_path)
    return backup_path


def backup_existing_configs(project_dir: Path) -> list[str]:
    """Back up existing generated config files. Returns list of informational messages."""
    messages: list[str] = []
    for filename in GENERATED_CONFIG_FILES:
        path = project_dir / filename
        backup = backup_file(path)
        if backup is not None:
            messages.append(f"Backed up {path.name} to {backup.name}")
    return messages


def _write_env_file(config: DeployConfig, target_dir: Path) -> None:
    """Write the generated environment file with restrictive permissions."""
    env_path = target_dir / DEFAULT_ENV_FILE
    env_path.write_text(build_env_content(config), encoding="utf-8")
    try:
        env_path.chmod(0o600)
    except OSError as exc:
        print(
            f"Warning: Could not set restrictive permissions on {DEFAULT_ENV_FILE}: {exc}",
            file=sys.stderr,
        )


def write_config_files(config: DeployConfig, project_dir: Path) -> None:
    """Write local deployment config files and clean up stale alternatives."""
    _write_env_file(config, project_dir)

    stale_files: list[str] = []

    if config.caddy_config is not None:
        caddyfile_path = project_dir / DEFAULT_CADDYFILE
        caddyfile_path.write_text(build_caddyfile_content(config.caddy_config), encoding="utf-8")
        stale_files.append(DEFAULT_NO_CADDY_COMPOSE_FILE)
        if config.caddy_public:
            override_path = project_dir / DEFAULT_CADDY_PUBLIC_COMPOSE_FILE
            override_path.write_text(
                build_caddy_public_compose_override_content(), encoding="utf-8"
            )
        else:
            stale_files.append(DEFAULT_CADDY_PUBLIC_COMPOSE_FILE)
    else:
        no_caddy_path = project_dir / DEFAULT_NO_CADDY_COMPOSE_FILE
        no_caddy_path.write_text(build_direct_compose_content(), encoding="utf-8")
        stale_files.append(DEFAULT_CADDY_PUBLIC_COMPOSE_FILE)

    for name in stale_files:
        with suppress(FileNotFoundError):
            (project_dir / name).unlink()


def _backup_bundle_configs(bundle_dir: Path) -> list[str]:
    """Back up generated bundle config files before overwriting them."""
    messages: list[str] = []
    for filename in BUNDLE_CONFIG_FILES:
        backup = backup_file(bundle_dir / filename)
        if backup is not None:
            messages.append(f"Backed up {filename} to {backup.name}")
    return messages


def _remote_bundle_commands(config: DeployConfig) -> dict[str, str]:
    """Build lifecycle commands for a remote deployment bundle."""
    return build_lifecycle_commands(
        deployment_mode=config.deployment_mode,
        use_caddy=config.caddy_config is not None,
        caddy_public=config.caddy_public,
        tarball_filename=config.tarball_filename,
    )


def _build_remote_readme_content(config: DeployConfig, commands: dict[str, str]) -> str:
    """Document how to use a generated remote deployment bundle."""
    lines = [
        "# Remote deployment bundle",
        "",
        "Copy this directory to the remote server, then run the commands below.",
        "",
        "Blog content is stored in `./content/` (created automatically on first start).",
        "",
    ]
    step = 1
    if config.deployment_mode == DEPLOY_MODE_REGISTRY:
        lines.append(
            f"{step}. Authenticate the remote server to your container registry if needed."
        )
        step += 1
        lines.append(f"{step}. {commands['pull']}")
        step += 1
    else:
        lines.append(f"{step}. {commands['load']}")
        step += 1
    lines.append(f"{step}. {commands['start']}")
    step += 1
    lines.append(f"{step}. {commands['status']}")
    lines.extend(
        [
            "",
            "Management commands:",
            f"- Stop: {commands['stop']}",
            f"- Status: {commands['status']}",
        ]
    )
    return "\n".join(lines) + "\n"


def write_bundle_files(config: DeployConfig, bundle_dir: Path) -> None:
    """Write a self-contained remote deployment bundle."""
    bundle_dir.mkdir(parents=True, exist_ok=True)
    _write_env_file(config, bundle_dir)

    stale_files: list[str] = []
    if config.caddy_config is not None:
        (bundle_dir / DEFAULT_CADDYFILE).write_text(
            build_caddyfile_content(config.caddy_config), encoding="utf-8"
        )
        (bundle_dir / DEFAULT_IMAGE_COMPOSE_FILE).write_text(
            build_image_compose_content(), encoding="utf-8"
        )
        stale_files.append(DEFAULT_IMAGE_NO_CADDY_COMPOSE_FILE)
        if config.caddy_public:
            (bundle_dir / DEFAULT_CADDY_PUBLIC_COMPOSE_FILE).write_text(
                build_caddy_public_compose_override_content(), encoding="utf-8"
            )
        else:
            stale_files.append(DEFAULT_CADDY_PUBLIC_COMPOSE_FILE)
    else:
        (bundle_dir / DEFAULT_IMAGE_NO_CADDY_COMPOSE_FILE).write_text(
            build_image_direct_compose_content(), encoding="utf-8"
        )
        stale_files.extend(
            [
                DEFAULT_CADDYFILE,
                DEFAULT_CADDY_PUBLIC_COMPOSE_FILE,
                DEFAULT_IMAGE_COMPOSE_FILE,
            ]
        )

    for name in stale_files:
        with suppress(FileNotFoundError):
            (bundle_dir / name).unlink()

    commands = _remote_bundle_commands(config)
    (bundle_dir / DEFAULT_REMOTE_README).write_text(
        _build_remote_readme_content(config, commands),
        encoding="utf-8",
    )


# ── Build and scan ───────────────────────────────────────────────────


def build_image(project_dir: Path, image_tag: str) -> None:
    """Build a Docker image with the requested tag."""
    _run_docker(project_dir, ["build", "--tag", image_tag, "."])


def scan_image(project_dir: Path, image_tag: str) -> None:
    """Scan a Docker image with Trivy."""
    _run_trivy(
        project_dir,
        [
            "image",
            "--scanners",
            "vuln",
            "--exit-code",
            "1",
            "--severity",
            "MEDIUM,HIGH,CRITICAL",
            image_tag,
        ],
    )


def build_and_scan(project_dir: Path, image_tag: str) -> None:
    """Build the Docker image and scan with Trivy before deployment."""
    build_image(project_dir, image_tag)
    scan_image(project_dir, image_tag)


def push_image(project_dir: Path, image_tag: str) -> None:
    """Push a Docker image to a registry."""
    _run_docker(project_dir, ["push", image_tag])


def save_image_tarball(project_dir: Path, image_tag: str, tarball_path: Path) -> None:
    """Export a Docker image to a tarball."""
    tarball_path.parent.mkdir(parents=True, exist_ok=True)
    _run_docker(project_dir, ["save", "--output", str(tarball_path), image_tag])


def _compose_base_args(config: DeployConfig) -> list[str]:
    """Build the shared docker compose CLI prefix for local deployments."""
    args = ["compose", "--env-file", ".env.production"]
    for filename in _compose_filenames(
        DEPLOY_MODE_LOCAL,
        use_caddy=config.caddy_config is not None,
        caddy_public=config.caddy_public,
    ):
        args.extend(["-f", filename])
    return args


def _compose_up_command(config: DeployConfig, *, build: bool = True) -> list[str]:
    """Build the docker compose up command for local deployments."""
    command = [*_compose_base_args(config), "up", "-d"]
    if build:
        command.append("--build")
    return command


def _compose_build_command(config: DeployConfig) -> list[str]:
    """Build the docker compose build command for local deployments."""
    return [*_compose_base_args(config), "build"]


def _run_compose_up(config: DeployConfig, project_dir: Path, *, build: bool = True) -> None:
    """Start containers via docker compose with the correct file arguments."""
    _run_docker(project_dir, _compose_up_command(config, build=build))


# ── Deploy orchestration ────────────────────────────────────────────


def deploy(config: DeployConfig, project_dir: Path) -> DeployResult:
    """Write deployment config, build, scan, and start containers."""
    if not (project_dir / "docker-compose.yml").exists():
        raise FileNotFoundError(f"Missing docker-compose.yml in {project_dir}")

    _validate_config(config)

    trivy_available = shutil.which("trivy") is not None
    if trivy_available:
        _run_trivy(project_dir, ["--version"])
    else:
        print(
            "Warning: Trivy is not installed or not available on PATH; skipping Docker image scan.",
            file=sys.stderr,
        )

    backup_messages = backup_existing_configs(project_dir)
    for msg in backup_messages:
        print(msg)

    if config.deployment_mode == DEPLOY_MODE_LOCAL:
        write_config_files(config, project_dir)

        if trivy_available:
            _run_docker(project_dir, _compose_build_command(config))
            scan_image(project_dir, LOCAL_IMAGE_TAG)
            _run_compose_up(config, project_dir, build=False)
        else:
            _run_compose_up(config, project_dir)

        return DeployResult(
            env_path=project_dir / DEFAULT_ENV_FILE,
            commands=build_lifecycle_commands(
                deployment_mode=config.deployment_mode,
                use_caddy=config.caddy_config is not None,
                caddy_public=config.caddy_public,
            ),
            bundle_path=None,
        )

    bundle_dir = project_dir / config.bundle_dir
    bundle_backup_messages = _backup_bundle_configs(bundle_dir)
    for msg in bundle_backup_messages:
        print(msg)

    image_tag = config.image_ref
    if image_tag is None:
        raise DeployError("IMAGE_REF is required for remote deployment modes")

    if trivy_available:
        build_and_scan(project_dir, image_tag)
    else:
        build_image(project_dir, image_tag)

    write_bundle_files(config, bundle_dir)

    if config.deployment_mode == DEPLOY_MODE_REGISTRY:
        push_image(project_dir, image_tag)
    else:
        save_image_tarball(project_dir, image_tag, bundle_dir / config.tarball_filename)

    return DeployResult(
        env_path=bundle_dir / DEFAULT_ENV_FILE,
        commands=_remote_bundle_commands(config),
        bundle_path=bundle_dir,
    )


# ── Dry run ──────────────────────────────────────────────────────────


def _mask_secrets(config: DeployConfig) -> DeployConfig:
    """Return a copy of config with secrets replaced by placeholders for display."""
    placeholder = "*" * 8
    return DeployConfig(
        secret_key=placeholder,
        admin_username=config.admin_username,
        admin_password=placeholder,
        trusted_hosts=config.trusted_hosts,
        trusted_proxy_ips=config.trusted_proxy_ips,
        host_port=config.host_port,
        host_bind_ip=config.host_bind_ip,
        caddy_config=config.caddy_config,
        caddy_public=config.caddy_public,
        expose_docs=config.expose_docs,
        deployment_mode=config.deployment_mode,
        image_ref=config.image_ref,
        bundle_dir=config.bundle_dir,
        tarball_filename=config.tarball_filename,
    )


def dry_run(config: DeployConfig) -> None:
    """Print generated config files without writing or deploying."""
    _validate_config(config)

    masked = _mask_secrets(config)

    print(f"=== {DEFAULT_ENV_FILE} ===")
    print(build_env_content(masked))

    caddy_config = config.caddy_config
    if config.deployment_mode == DEPLOY_MODE_LOCAL and caddy_config is None:
        print(f"=== {DEFAULT_NO_CADDY_COMPOSE_FILE} ===")
        print(build_direct_compose_content())
    elif config.deployment_mode == DEPLOY_MODE_LOCAL and caddy_config is not None:
        print(f"=== {DEFAULT_CADDYFILE} ===")
        print(build_caddyfile_content(caddy_config))
        if config.caddy_public:
            print(f"=== {DEFAULT_CADDY_PUBLIC_COMPOSE_FILE} ===")
            print(build_caddy_public_compose_override_content())
    elif caddy_config is not None:
        print(f"=== {DEFAULT_CADDYFILE} ===")
        print(build_caddyfile_content(caddy_config))
        print(f"=== {DEFAULT_IMAGE_COMPOSE_FILE} ===")
        print(build_image_compose_content())
        if config.caddy_public:
            print(f"=== {DEFAULT_CADDY_PUBLIC_COMPOSE_FILE} ===")
            print(build_caddy_public_compose_override_content())
    else:
        print(f"=== {DEFAULT_IMAGE_NO_CADDY_COMPOSE_FILE} ===")
        print(build_image_direct_compose_content())

    use_caddy = config.caddy_config is not None
    commands = build_lifecycle_commands(
        deployment_mode=config.deployment_mode,
        use_caddy=use_caddy,
        caddy_public=config.caddy_public,
        tarball_filename=config.tarball_filename,
    )
    print("=== Lifecycle commands ===")
    if "pull" in commands:
        print(f"  Pull:   {commands['pull']}")
    if "load" in commands:
        print(f"  Load:   {commands['load']}")
    print(f"  Start:  {commands['start']}")
    print(f"  Stop:   {commands['stop']}")
    print(f"  Status: {commands['status']}")


# ── Interactive prompts ──────────────────────────────────────────────


def _prompt_non_empty(prompt: str, default: str | None = None) -> str:
    """Prompt until a non-empty string is provided."""
    while True:
        suffix = f" [{default}]" if default is not None else ""
        value = input(f"{prompt}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        print("Value cannot be empty.")


def _prompt_yes_no(prompt: str, default: bool) -> bool:
    """Prompt for a yes/no answer."""
    suffix = "[Y/n]" if default else "[y/N]"
    while True:
        value = input(f"{prompt} {suffix}: ").strip().lower()
        if not value:
            return default
        if value in {"y", "yes"}:
            return True
        if value in {"n", "no"}:
            return False
        print("Please answer yes or no.")


def _prompt_deployment_mode() -> str:
    """Prompt for a supported deployment mode."""
    prompt = f"Deployment mode [local/registry/tarball] [{DEPLOY_MODE_LOCAL}]"
    while True:
        value = input(f"{prompt}: ").strip().lower()
        if not value:
            return DEPLOY_MODE_LOCAL
        if value in DEPLOY_MODES:
            return value
        print("Please choose local, registry, or tarball.")


def _prompt_host_port(default: int = DEFAULT_HOST_PORT) -> int:
    """Prompt for a valid host port."""
    while True:
        raw = input(f"Host port for AgBlogger [{default}]: ").strip()
        if not raw:
            return default
        if raw.isdigit():
            value = int(raw)
            if 1 <= value <= 65535:
                return value
        print("Please enter a valid port in range 1-65535.")


def _prompt_secret_key() -> str:
    """Prompt for secret key or auto-generate one."""
    secret_key = getpass.getpass(
        "SECRET_KEY (leave blank to auto-generate a random value): "
    ).strip()
    if not secret_key:
        generated = secrets.token_urlsafe(64)
        print("Generated SECRET_KEY automatically.")
        return generated

    if len(secret_key) < MIN_SECRET_KEY_LENGTH:
        print(f"SECRET_KEY must be at least {MIN_SECRET_KEY_LENGTH} characters.")
        return _prompt_secret_key()
    return secret_key


def _prompt_password() -> str:
    """Prompt for admin password with confirmation."""
    while True:
        password = getpass.getpass("Admin password: ").strip()
        if len(password) < MIN_ADMIN_PASSWORD_LENGTH:
            print(f"Password must be at least {MIN_ADMIN_PASSWORD_LENGTH} characters.")
            continue
        confirmation = getpass.getpass("Confirm admin password: ").strip()
        if password != confirmation:
            print("Passwords do not match.")
            continue
        return password


def collect_config() -> DeployConfig:
    """Collect interactive production settings from the user."""
    print("Enter production configuration values for your blog server.")
    secret_key = _prompt_secret_key()
    admin_username = _prompt_non_empty("Admin username", default="admin")
    admin_password = _prompt_password()
    deployment_mode = _prompt_deployment_mode()
    image_ref: str | None = None
    tarball_filename = DEFAULT_IMAGE_TARBALL
    if deployment_mode in {DEPLOY_MODE_REGISTRY, DEPLOY_MODE_TARBALL}:
        image_ref = _prompt_non_empty("Container image reference")
        if deployment_mode == DEPLOY_MODE_TARBALL:
            tarball_filename = _prompt_non_empty(
                "Tarball filename",
                default=DEFAULT_IMAGE_TARBALL,
            )

    use_caddy = _prompt_yes_no(
        (
            "Set up HTTPS with Caddy? "
            "Caddy is a web server that automatically handles TLS certificates "
            "and forwards traffic to AgBlogger"
        ),
        default=True,
    )

    caddy_config: CaddyConfig | None = None
    host_port = DEFAULT_HOST_PORT
    caddy_public = False
    if use_caddy:
        caddy_domain = _prompt_non_empty("Public domain for your blog (example: blog.example.com)")
        caddy_email = input("Email for TLS certificate notices (optional, recommended): ").strip()
        caddy_config = CaddyConfig(domain=caddy_domain, email=caddy_email or None)
        caddy_public = _prompt_yes_no(
            "Expose Caddy ports 80/443 publicly so your site is Internet-reachable?",
            default=True,
        )
        host_bind_ip = LOCALHOST_BIND_IP
        print(
            "\nNote: Ensure your domain's DNS A/AAAA record points to this server"
            " before starting. Caddy needs to reach Let's Encrypt to provision"
            " TLS certificates.\n"
        )
    else:
        host_bind_ip = (
            PUBLIC_BIND_IP
            if _prompt_yes_no(
                "Expose AgBlogger directly on the Internet (without Caddy)?",
                default=True,
            )
            else LOCALHOST_BIND_IP
        )
        host_port = _prompt_host_port()

    trusted_hosts: list[str] = []
    while not trusted_hosts:
        raw_hosts = input(
            "Hostnames/IPs clients will use to reach your blog"
            " (comma-separated, validates the Host header): "
        ).strip()
        trusted_hosts = parse_csv_list(raw_hosts)
        if caddy_config and caddy_config.domain not in trusted_hosts:
            trusted_hosts.append(caddy_config.domain)
        if not trusted_hosts:
            print("Provide at least one trusted host.")

    if use_caddy:
        proxy_ips = [COMPOSE_SUBNET]
        extra_proxy_ips = parse_csv_list(
            input("Additional trusted proxy IPs (comma-separated, optional): ").strip()
        )
        for ip in extra_proxy_ips:
            if ip not in proxy_ips:
                proxy_ips.append(ip)
        print(f"Caddy proxy subnet ({COMPOSE_SUBNET}) auto-configured as a trusted proxy.")
    else:
        proxy_ips = parse_csv_list(input("Trusted proxy IPs (comma-separated, optional): ").strip())

    expose_docs = _prompt_yes_no(
        "Expose API documentation at /docs? (usually only for development)",
        default=False,
    )

    return DeployConfig(
        secret_key=secret_key,
        admin_username=admin_username,
        admin_password=admin_password,
        trusted_hosts=trusted_hosts,
        trusted_proxy_ips=proxy_ips,
        host_port=host_port,
        host_bind_ip=host_bind_ip,
        caddy_config=caddy_config,
        caddy_public=caddy_public,
        expose_docs=expose_docs,
        deployment_mode=deployment_mode,
        image_ref=image_ref,
        bundle_dir=DEFAULT_BUNDLE_DIR,
        tarball_filename=tarball_filename,
    )


# ── Non-interactive config from CLI arguments ────────────────────────


def config_from_args(args: argparse.Namespace) -> DeployConfig:
    """Build DeployConfig from CLI arguments for non-interactive mode."""
    secret_key = args.secret_key or secrets.token_urlsafe(64)
    if not args.admin_username:
        raise DeployError("--admin-username is required in non-interactive mode")
    admin_password = args.admin_password or os.environ.get("ADMIN_PASSWORD", "")
    if not admin_password:
        raise DeployError(
            "--admin-password is required (or set ADMIN_PASSWORD env var) in non-interactive mode"
        )
    if not args.trusted_hosts:
        raise DeployError("--trusted-hosts is required in non-interactive mode")
    if args.deployment_mode in {DEPLOY_MODE_REGISTRY, DEPLOY_MODE_TARBALL} and not args.image_ref:
        raise DeployError("--image-ref is required for registry and tarball deployment modes")

    caddy_config: CaddyConfig | None = None
    caddy_public = False
    if args.caddy_domain:
        caddy_config = CaddyConfig(domain=args.caddy_domain, email=args.caddy_email)
        caddy_public = args.caddy_public
        host_bind_ip = LOCALHOST_BIND_IP
    else:
        host_bind_ip = PUBLIC_BIND_IP if args.bind_public else LOCALHOST_BIND_IP

    trusted_hosts = parse_csv_list(args.trusted_hosts)
    if caddy_config and caddy_config.domain not in trusted_hosts:
        trusted_hosts.append(caddy_config.domain)

    trusted_proxy_ips = parse_csv_list(args.trusted_proxy_ips) if args.trusted_proxy_ips else []
    if caddy_config is not None and COMPOSE_SUBNET not in trusted_proxy_ips:
        trusted_proxy_ips.insert(0, COMPOSE_SUBNET)

    return DeployConfig(
        secret_key=secret_key,
        admin_username=args.admin_username,
        admin_password=admin_password,
        trusted_hosts=trusted_hosts,
        trusted_proxy_ips=trusted_proxy_ips,
        host_port=args.host_port,
        host_bind_ip=host_bind_ip,
        caddy_config=caddy_config,
        caddy_public=caddy_public,
        expose_docs=args.expose_docs,
        deployment_mode=args.deployment_mode,
        image_ref=args.image_ref,
        bundle_dir=args.bundle_dir,
        tarball_filename=args.tarball_filename,
    )


# ── CLI entry point ──────────────────────────────────────────────────


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Production deployment helper for AgBlogger.",
    )
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=Path.cwd(),
        help="Project directory containing docker-compose.yml (default: current directory).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated config files without writing or deploying.",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Run without interactive prompts; requires all config via CLI arguments.",
    )

    config_group = parser.add_argument_group("configuration")
    config_group.add_argument("--secret-key", help="JWT signing key (auto-generated if omitted).")
    config_group.add_argument("--admin-username", help="Initial admin username.")
    config_group.add_argument(
        "--admin-password",
        help="Initial admin password. Also accepted via ADMIN_PASSWORD env var.",
    )
    config_group.add_argument(
        "--caddy-domain",
        help="Enable Caddy HTTPS with this domain. Omit to expose AgBlogger directly.",
    )
    config_group.add_argument("--caddy-email", help="Email for TLS certificate notifications.")
    config_group.add_argument(
        "--caddy-public",
        action="store_true",
        default=False,
        help="Expose Caddy ports 80/443 publicly (default: localhost only).",
    )
    config_group.add_argument(
        "--trusted-hosts",
        help="Comma-separated hostnames/IPs for Host header validation.",
    )
    config_group.add_argument(
        "--trusted-proxy-ips",
        help="Comma-separated trusted proxy IPs (optional).",
    )
    config_group.add_argument(
        "--host-port",
        type=int,
        default=DEFAULT_HOST_PORT,
        help=f"Host port for AgBlogger (default: {DEFAULT_HOST_PORT}).",
    )
    config_group.add_argument(
        "--bind-public",
        action="store_true",
        default=False,
        help="Bind to 0.0.0.0 instead of 127.0.0.1 (only for non-Caddy mode).",
    )
    config_group.add_argument(
        "--expose-docs",
        action="store_true",
        default=False,
        help="Expose API documentation at /docs (default: disabled).",
    )
    config_group.add_argument(
        "--deployment-mode",
        choices=sorted(DEPLOY_MODES),
        default=DEPLOY_MODE_LOCAL,
        help="Choose local deploy, registry bundle, or tarball bundle mode.",
    )
    config_group.add_argument(
        "--image-ref",
        help="Container image reference for registry or tarball deployment modes.",
    )
    config_group.add_argument(
        "--bundle-dir",
        type=Path,
        default=DEFAULT_BUNDLE_DIR,
        help=f"Output directory for remote deployment bundles (default: {DEFAULT_BUNDLE_DIR}).",
    )
    config_group.add_argument(
        "--tarball-filename",
        default=DEFAULT_IMAGE_TARBALL,
        help=f"Image tarball name for tarball deployment mode (default: {DEFAULT_IMAGE_TARBALL}).",
    )

    return parser.parse_args()


def main() -> None:
    """Run deployment workflow."""
    args = _parse_args()
    project_dir = args.project_dir.resolve()

    try:
        config = config_from_args(args) if args.non_interactive else collect_config()

        if args.dry_run:
            dry_run(config)
            return

        check_prerequisites(project_dir)
        result = deploy(config=config, project_dir=project_dir)
    except (DeployError, FileNotFoundError) as exc:
        print(f"Deployment failed: {exc}")
        sys.exit(1)
    except subprocess.CalledProcessError as exc:
        cmd_str = " ".join(exc.cmd) if isinstance(exc.cmd, list) else str(exc.cmd)
        print(f"Deployment failed (exit code {exc.returncode}): {cmd_str}")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nDeployment cancelled.")
        sys.exit(1)

    print("\nDeployment complete.")
    print(f"Environment file: {result.env_path}")
    if result.bundle_path is not None:
        print(f"Remote bundle: {result.bundle_path}")
    print("Use these commands to manage the server:")
    if "pull" in result.commands:
        print(f"  Pull:   {result.commands['pull']}")
    if "load" in result.commands:
        print(f"  Load:   {result.commands['load']}")
    print(f"  Start:  {result.commands['start']}")
    print(f"  Stop:   {result.commands['stop']}")
    print(f"  Status: {result.commands['status']}")
    if config.deployment_mode == DEPLOY_MODE_LOCAL:
        if config.caddy_config is not None:
            print(f"Open the app at: https://{config.caddy_config.domain}/login")
        else:
            print(f"Open the app at: http://<your-server-host>:{config.host_port}/login")
    else:
        print("Follow the bundle instructions on the remote server to finish deployment.")


if __name__ == "__main__":
    main()
