class CrawlerDetect:
    def __init__(
        self, headers: dict[str, str] | None = None, user_agent: str = ""
    ) -> None: ...
    def is_crawler(self, user_agent: str | None = None) -> bool: ...
